version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'apartments'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
    volumes:
      - ./backend/database/data.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  server:
    container_name: server
    restart: always
    build: ./backend
    environment:
      - PORT=5000
      - DB_NAME=apartments
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  client:
    container_name: client
    build: frontend
    image: node
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - '.:/app'
      - '/app/node_modules'
    restart: always

    ports:
      - "8080:8080"
    depends_on:
      - server